---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: prometheus
type: Opaque
stringData:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: devops
      routes:
      - match:
          team: devops
        receiver: devops
      - match:
          team: developers
        receiver: developers

    receivers:
    - name: devops
      webhook_configs:
      - url: "http://prometheus-msteams:2000/devops"
        send_resolved: true
    - name: developers
      webhook_configs:
      - url: "http://prometheus-msteams:2000/developers"
        send_resolved: true
