{
 "title": "Kubernetes All Pods",
 "tags": [ "pods" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_labels, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=~\"$namespace\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$namespace\",pod=~\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\",namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\", container!=\"POD\", container!=\"\"}",
     "legendFormat": "Requested: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\",namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\", container!=\"POD\", container!=\"\"}",
     "legendFormat": "Limit: {{ pod }}"
    },
    {
     "expr": "container_memory_usage_bytes{namespace=\"$namespace\",pod=\"$pod\",container=~\"$container\", container!=\"POD\", container!=\"\"}",
     "legendFormat": "Usage: {{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{resource=\"cpu\", namespace=\"$namespace\", pod=\"$pod\",container=~\"$container\",container!=\"POD\", container!=\"\"}) by (pod,container)",
     "legendFormat": "Request: {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", container!=\"POD\", container!=\"\"}) by (pod,container)",
     "legendFormat": "Limit: {{ pod }}"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container=~\"$container\", container!=\"POD\", container!=\"\"}[2m])) by (pod,container)",
     "legendFormat": "Usage: {{ pod }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod) (rate (container_network_receive_bytes_total{pod=\"$pod\"}[5m]) ))",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}