---
# Role binding <> Cluster role
# All service accounts, from the namespace "kube-system", assign "privileged" Pod Security Policy
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts