---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: io1
  # annotations:
  #   storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: io1
  iopsPerGB: "100"
  fsType: "ext4"
  # encrypted: "true"
  # kmsKeyId: arn:aws:kms:............
mountOptions:
  - debug